-- Shop&Drop V24.2.2: Handmade Furniture & Woodwork taxonomy extension
-- Adds dedicated handmade furniture branches without duplicating the master Home/Furniture catalogue.

INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Tables & Desks','arts-crafts-handmade-handmade-furniture-tables-and-desks',p.id,5 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-tables-and-desks');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Chairs & Benches','arts-crafts-handmade-handmade-furniture-chairs-and-benches',p.id,6 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-chairs-and-benches');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Shelving & Storage','arts-crafts-handmade-handmade-furniture-shelving-and-storage',p.id,7 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-shelving-and-storage');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Cabinets & Cupboards','arts-crafts-handmade-handmade-furniture-cabinets-and-cupboards',p.id,8 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-cabinets-and-cupboards');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Beds & Bedroom Furniture','arts-crafts-handmade-handmade-furniture-beds-and-bedroom-furniture',p.id,9 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-beds-and-bedroom-furniture');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Outdoor & Garden Furniture','arts-crafts-handmade-handmade-furniture-outdoor-and-garden-furniture',p.id,10 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-outdoor-and-garden-furniture');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Children’s Furniture','arts-crafts-handmade-handmade-furniture-childrens-furniture',p.id,11 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-childrens-furniture');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Custom & Bespoke Furniture','arts-crafts-handmade-handmade-furniture-custom-and-bespoke-furniture',p.id,12 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-custom-and-bespoke-furniture');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Woodwork & Decorative Pieces','arts-crafts-handmade-handmade-furniture-woodwork-and-decorative-pieces',p.id,13 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-woodwork-and-decorative-pieces');
INSERT INTO categories(name,slug,parent_id,sort_order) SELECT 'Handmade Furniture — Other','arts-crafts-handmade-handmade-furniture-other',p.id,14 FROM categories p WHERE p.slug='arts-crafts-handmade' AND NOT EXISTS(SELECT 1 FROM categories WHERE slug='arts-crafts-handmade-handmade-furniture-other');
